pymongo.errors.ServerSelectionTimeoutError: 
SSL handshake failed: cluster0-shard-00-02.x3l7f.mongodb.net:27017: [
SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) 
(configured timeouts: socketTimeoutMS: 20000.0ms, 
connectTimeoutMS: 20000.0ms),
SSL handshake failed: cluster0-shard-00-00.x3l7f.mongodb.net:27017: 
[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) 
(configured timeouts: socketTimeoutMS: 20000.0ms, 
connectTimeoutMS: 20000.0ms),
SSL handshake failed: cluster0-shard-00-01.x3l7f.mongodb.net:27017:
 [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) 
 (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), 
 Timeout: 30s, 
 
 Topology Description: <TopologyDescription id: 657763976fa633f6374974d7, topology_type: ReplicaSetNoPrimary, 
 
 servers: [<ServerDescription ('cluster0-shard-00-00.x3l7f.mongodb.net', 27017) 
 server_type: Unknown, 
 rtt: None, 
 error=AutoReconnect('SSL handshake failed: cluster0-shard-00-00.x3l7f.mongodb.net:27017: 
 [SSL: TLSV1_ALERT_INTERNAL_ERROR] 
 tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-01.x3l7f.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: cluster0-shard-00-01.x3l7f.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('cluster0-shard-00-02.x3l7f.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: cluster0-shard-00-02.x3l7f.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>